language: go

sudo: false

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.16.x
  - 1.17.x
  - tip

before_install:
  - if `go version | grep -Eq 'go1\.(9|10|11|12|13|14|15)\.'`; then
    go get github.com/mattn/goveralls;
    go get golang.org/x/tools/cmd/cover;
    else
    go install github.com/mattn/goveralls@v0.0.11;
    go install golang.org/x/tools/cmd/cover@v0.1.1;
    fi
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
